package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.25

import (
	"context"
	"fmt"
	"go-gql-sample/app/internal/infrastructure/server/graph"
	"go-gql-sample/app/internal/infrastructure/server/graph/model"
)

// Todo is the resolver for the todo field.
func (r *queryResolver) Todo(ctx context.Context, id *int) (*model.Todo, error) {
	panic(fmt.Errorf("not implemented: Todo - todo"))
}

// TodoPagination is the resolver for the todoPagination field.
func (r *queryResolver) TodoPagination(ctx context.Context, limit int, offset *int) (*model.TodoPagination, error) {
	panic(fmt.Errorf("not implemented: TodoPagination - todoPagination"))
}

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
